apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.basmu.bucket.name=${BUCKET_NAME}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.osm.poi.folder=osm
    blobstore.gcs.haya.bucket.name={{ .Values.gcs.haya.bucketName }}
    blobstore.gcs.haya.latest.filename_without_extension=basmu_latest
    blobstore.gcs.haya.import.folder=import
    spring.profiles.active=gcs-blobstore
    spring.application.name=basmu
    spring.main.web-application-type=NONE
    basmu.retry.maxAttempts=3
    basmu.retry.maxDelay=5000
    basmu.retry.backoff.multiplier=3
    osmpoifilters.service.url={{ .Values.osmpoifilters.service.url }}
metadata:
  name: {{ template "basmu.name" . }}-config
  namespace: {{ template "basmu.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}