apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.basmu.bucket.name=${BUCKET_NAME}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.osm.poi.folder=osm
    blobstore.gcs.haya.bucket.name={{ .Values.gcs.haya.bucketName }}
    blobstore.gcs.haya.latest.filename_without_extension=basmu_latest
    blobstore.gcs.haya.import.folder=import
    spring.profiles.active=gcs-blobstore
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoints.web.exposure.include=health
    management.endpoints.jmx.exposure.exclude=*
    spring.cloud.task.closecontextEnabled=true
    spring.application.name=basmu
    logging.level.org.springframework.cloud.task=DEBUG
metadata:
  name: {{ template "basmu.name" . }}-config
  namespace: {{ template "basmu.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}